name: Deploy Angular Frontend

on:
  push:
    branches:
      - develop  # Cambia a 'main' si es tu rama de producción

jobs:
  deploy-frontend:
    runs-on: self-hosted
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy with Docker Compose
        run: |
          sudo docker compose down --remove-orphans
          sudo docker compose up -d --build frontend
